development:
  adapter: postgresql
  encoding: unicode
  database: nouvresto
  pool: 5
  username: jean-claude
  password: flc
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: flcprod
  pool: 5
  username: jcl
  password: flc
  timeout: 5000

staging:
  adapter: postgresql
  encoding: unicode
  database: restau20150218
  pool: 5
  username: jcl
  password: flc
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: pgtestflc
  pool: 5
  username: jean-claude
  password:
  timeout: 5000
