# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ab677e9a336ed0dab8d6889fc7f4fc2af8a6744c981c4874a45d4bd362f499f3d425b4d994ff50d7a09264271a61e273082bff66ce81f3006b2eebcac1b53f7

test:
  secret_key_base: 2aeff6c5f625fd9543b1eee2cf2578f37ee2f6a25e12ded8432ed4eb88be76fc1a199d7bd61a21817dfbc50d95e3dee4d0ebc67e86dab9dc3a8588fd028fb6bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
